version: "3"

services:
  nginx:
    image: nginx:1.17-alpine
    restart: always
    ports:
      - "5678:80"
    volumes:
      - ./server_config/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./public:/usr/share/nginx/html:ro
  php:
    build: .
    restart: always
    volumes:
      - .:/var/www/dayou
    working_dir: /var/www/dayou
