version: "3"

services:
  php:
    build: .
    ports:
      - "5678:8000"
    volumes:
      - .:/var/www/dayou
    working_dir: /var/www/dayou
    command: php artisan serve --host 0.0.0.0
  database:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: "otnxgYQSRRELEEUdZBQJ1MDYoRGiqIMF"
      MYSQL_DATABASE: "dayou"
    ports:
      - "3306:3306"
    volumes:
      - ./server_config/mysqld.cnf:/etc/mysql/conf.d/mysqld.cnf
      - dbdata:/var/lib/mysql
  redis:
    image: redis:5.0-alpine
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data
volumes:
  dbdata:
  redisdata:
